### ISSUE TITLE
Sorting of Items

### ISSUE THREAD

**Issue by nist24** [poirazis/bb-component-SuperSideNavigation#1]
Thanks Michael for this awesome plugin!
Is there a way to define the sorting of the items when using a data provider?

Kind regards,
Nicolas

**Comment by poirazis** [comment]
Hello @nist24 
Currently the Data Provider doesn't "sort" relationship / array fields.
That would require the component to make the sorting.
Let me have a go at it and revert!

**Comment by nist24** [comment]
Hi @poirazis 
It would be great if you could implement this when you find some time.

**Comment by poirazis** [comment]
Hey @nist24 
the component has been updated to support Item Sorting
please update to version 1.3.0
Enjoy !
