### ISSUE TITLE
Features: Support icon

### ISSUE THREAD

**Issue by ryzam** [poirazis/bb-component-SuperSideNavigation#2]
Hi,

Any plan to support icon on the navigation menu?

**Comment by poirazis** [comment]
hay @ryzam 
do you mean same icon for all items or each item to have its own ?

**Comment by ryzam** [comment]
Each item can have its own icon, it's normal features in any navigation side menu.

**Comment by poirazis** [comment]
i know, but budibase doesn't have custom propertes yet, so there is no way to allow the user to select a different icon for each itam. as soon as the option comes to budibase, i will surely implement this
